#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

START=70
. /etc/nrpe/uciparse
SERVICE_USE_PID=1

start() {
	config_load nrpe
	do_options 
        user_exists $user $uid || user_add $user $uid
	group_exists $group $gid || group_add $group $gid
	[ -d $rundir ] || {
		mkdir -m 0755 -p $rundir
		chown $user:$group $rundir
	}
	service_start /usr/sbin/nrpe -c $tmpconf -d
}

stop() {
	service_stop /usr/sbin/nrpe
}
