#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

START=70
. /etc/nrpe/uciparse
SERVICE_USE_PID=1
start() {
        genconf
        user_exists $user $uid || user_add $user $uid
        group_exists $group $gid || group_add $group $gid
        [ -d $rundir ] || {
                mkdir -m 0777 -p $rundir
                chown $user:$group $rundir
        }
        piddir=$(dirname $pidfile)
	mkdir -p $piddir
	chown $user $piddir
	service_start /usr/sbin/nrpe -c $tmpconf -d
}

stop() {
        config_load nrpe
	config_get pidfile options pidfile /var/run/nrpe/nrpe.pid
	kill $(cat $pidfile)
	#service_stop /usr/sbin/nrpe
}

