#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
. /etc/syslog-ng/uciparse

start() {
        genconf
        service_start /usr/sbin/syslog-ng -f $tmpconf
}

stop() {
        service_stop /usr/sbin/syslog-ng
}

reload() {
        service_reload /usr/sbin/syslog-ng
}

